language: go

go:
  - 1.7.5

os:
  - linux

sudo: required
dist: trusty

before_install:
  - sudo apt-get autoclean
  - sudo apt-get autoremove

install:
  - sudo -E make apt
  - make submodules
  - make pip
  - make dev_setup_runtime
  - make -C app/tests testing.id_rsa
  - make front

before_script:
  - make assets

  - sudo -E make aci_core
  - sudo -E make container_linux

  - make config

script:
  - make check
  - SKIP_ACSERVER=y make validate

# If we are in the private repo, publish success on the public one
after_success:
  - ./.ci/travis.sh