language: python

python:
  - "2.7"

os:
  - linux

sudo: required
dist: trusty

before_install:
  - sudo apt-get autoclean
  - sudo apt-get autoremove
  - sudo apt-get update
  - sudo apt-get upgrade

install:
  - sudo make apt

before_script:
  - sudo MY_USER=travis make dev_setup

script:
  - make check
  - make validate

# If we are in the private repo, publish success on the public one
after_success:
  - ./.ci/travis.sh