os:
  - linux

sudo: required
dist: trusty

install:
  - sudo apt-get update -q

script:
  - sudo make apt

  - make submodules
  - make runner

  - sudo make acis

  - make assets
  - make validate
  - make check
  - make validate
