os:
  - linux

sudo: required
dist: trusty


before_install:
  - git checkout ${TRAVIS_BRANCH}
  - git pull

install:
  - sudo apt-get update -q
  - DEBIAN_FRONTEND=noninteractive sudo apt-get install -y curl python python-virtualenv jq file make

before_script:
  - make submodules
  - sudo make acis

script:
  - sudo make release_aci
