os:
  - linux

sudo: required
dist: trusty

before_install:
  - sudo apt-get update -q
  - DEBIAN_FRONTEND=noninteractive sudo apt-get install -y curl python python-virtualenv jq file make

script:
  - sudo make acis
  - sudo make release_aci
