language: generic

os:
  - linux

sudo: required
dist: trusty

install:
  - sudo apt-get update -q

script:
  - sudo make apt

  - sudo MY_USER=travis make setup
  - make check
  - make validate

after_success:
  - ./ci.travis.sh