language: go

go:
  - 1.7.5

os:
  - linux

sudo: required
dist: trusty

before_install:
  - sudo apt-get autoclean
  - sudo apt-get autoremove

install:
  - sudo -E make apt

before_script:
  - sudo -E MY_USER=travis make dev_setup

script:
  - make check
  - make validate

# If we are in the private repo, publish success on the public one
after_success:
  - ./.ci/travis.sh